### ISSUE TITLE
Centos_6 CI is failing

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-buildtools-prereqs-docker#19]
12:50:08 Step 5/7 : RUN wget http://download.icu-project.org/files/icu4c/57.1/icu4c-57_1-RHEL6-x64.tgz &&     tar -xf icu4c-57_1-RHEL6-x64.tgz -C / &&     rm icu4c-57_1-RHEL6-x64.tgz
12:50:09  ---> Running in d16807219e28
12:50:09 [91m--2018-03-01 20:50:09--  http://download.icu-project.org/files/icu4c/57.1/icu4c-57_1-RHEL6-x64.tgz
12:50:09 Resolving download.icu-project.org... [0m[91m208.109.101.195
12:50:09 Connecting to download.icu-project.org|208.109.101.195|:80... [0m[91mconnected.
12:50:09 HTTP request sent, awaiting response... [0m[91m302 Found
12:50:09 Location: https://downloads.sourceforge.net/project/icu/ICU4C/57.1/icu4c-57_1-RHEL6-x64.tgz [following]
12:50:09 --2018-03-01 20:50:09--  https://downloads.sourceforge.net/project/icu/ICU4C/57.1/icu4c-57_1-RHEL6-x64.tgz
12:50:09 [0m[91mResolving downloads.sourceforge.net... [0m[91m52.85.131.102, 52.85.131.22, 52.85.131.167, ...
12:50:09 Connecting to downloads.sourceforge.net|52.85.131.102|:443... [0m[91mconnected.
12:50:09 [0m[91mHTTP request sent, awaiting response... [0m[91m302 Moved Temporarily
12:50:10 Location: https://downloads.sourceforge.net/#!/project/icu/ICU4C/57.1/icu4c-57_1-RHEL6-x64.tgz [following]
12:50:10 --2018-03-01 20:50:10--  https://downloads.sourceforge.net/
12:50:10 [0m[91mReusing existing connection to downloads.sourceforge.net:443.
12:50:10 HTTP request sent, awaiting response... [0m[91m200 OK
12:50:10 Length: 652 [text/html]
12:50:10 Saving to: `icu4c-57_1-RHEL6-x64.tgz'
12:50:10 
12:50:10      0K                                                       [0m[91m100%  194M=0s
12:50:10 
12:50:10 [0m[91m2018-03-01 20:50:10 (194 MB/s) - `icu4c-57_1-RHEL6-x64.tgz' saved [652/652]
12:50:10 
12:50:10 [0m[91m
12:50:10 gzip: stdin: not in gzip format
12:50:10 [0m[91mtar: Child returned status 1
12:50:10 tar: Error is not recoverable: exiting now
12:50:10 [0mThe command '/bin/sh -c wget http://download.icu-project.org/files/icu4c/57.1/icu4c-57_1-RHEL6-x64.tgz &&     tar -xf icu4c-57_1-RHEL6-x64.tgz -C / &&     rm icu4c-57_1-RHEL6-x64.tgz' returned a non-zero code: 2
12:50:10 System.InvalidOperationException: Failed to execute docker build -t microsoft/dotnet-buildtools-prereqs:centos-6-d770b8b-20180301200846 -f src/centos/6/Dockerfile src/centos/6
12:50:10    at Microsoft.DotNet.ImageBuilder.ExecuteHelper.Execute(ProcessStartInfo info, Func`2 executor, Boolean isDryRun, String errorMessage, String executeMessageOverride) in /image-builder/src/ExecuteHelper.cs:line 69
12:50:10    at Microsoft.DotNet.ImageBuilder.Commands.BuildCommand.BuildImages() in /image-builder/src/Commands/BuildCommand.cs:line 61
12:50:10    at Microsoft.DotNet.ImageBuilder.Commands.BuildCommand.ExecuteAsync() in /image-builder/src/Commands/BuildCommand.cs:line 28
12:50:10    at Microsoft.DotNet.ImageBuilder.ImageBuilder.Main(String[] args) in /image-builder/src/ImageBuilder.cs:line 53

**Comment by MichaelSimons** [comment]
It looks as though this was an intermittent (service side) issue.  centos_6 CI is passing now - https://ci.dot.net/job/dotnet_dotnet-buildtools-prereqs-docker/job/master/job/centos_6_prtest/10/
