### ISSUE TITLE
Ubuntu 18.04 Dockerfile fails to build while installing the azure-cli

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-buildtools-prereqs-docker#219]
Snippet from build output while building https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/master/src/ubuntu/18.04/amd64/Dockerfile#L32

```
[91mnpm[0m[91m [0m[91mWARN [0m[91mdeprecated[0m[91m azure-common@0.9.18: The SDK is deprecated next year and is replaced by a new TypeScript-based isomorphic SDK. See https://aka.ms/azure-sdk-for-js-migration to learn more.
[0m[91mnpm WARN[0m[91m deprecated github@0.1.6: 'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)
[0m[91mnpm WARN [0m[91mdeprecated node-uuid@1.4.7: Use uuid module instead
[0m[91mnpm WARN deprecated node-uuid@1.4.8: Use uuid module instead
[0m[91mnpm [0m[91mWARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
[0m[91mnpm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
[0m[91mnpm WARN[0m[91m deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
[0m[91mnpm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
[0m[91mnpm WARN[0m[91m deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
[0m[91mnpm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
[0m[91mnpm ERR! Linux 4.15.0-1064-azure
[0m[91mnpm [0m[91mERR![0m[91m argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "azure-cli@0.10.15"
[0m[91mnpm [0m[91mERR![0m[91m node[0m[91m v8.10.0
[0m[91mnpm[0m[91m [0m[91mERR![0m[91m npm [0m[91m v3.5.2
[0m[91mnpm ERR! code EMISSINGARG
[0m[91m
[0m[91mnpm ERR! typeerror Error: Missing required argument #1
npm ERR![0m[91m [0m[91mtypeerror[0m[91m     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
[0m[91mnpm[0m[91m ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm [0m[91mERR![0m[91m typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
[0m[91mnpm[0m[91m ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
[0m[91m
npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
```

**Comment by MichaelSimons** [comment]
From my investigation, the npm packages for azure-cli haven't been updated for a year.  The recommended way to install the CLI on Ubuntu is from apt-get.
