### ISSUE TITLE
Debian 9 Helix builds failing when installing Python

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-buildtools-prereqs-docker#402]
Builds for the following Dockerfiles are failing:
* https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/master/src/debian/9/helix/arm32v7/Dockerfile
* https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/master/src/debian/9/helix/arm64v8/Dockerfile

Example Docker build output:

```
Step 1/7 : FROM arm64v8/debian:9
 ---> 5c3de08836c6
Step 2/7 : RUN apt-get update &&     apt-get install -y         autoconf         automake         at         build-essential         curl         gcc         gdb         git         iputils-ping         libcurl3         libffi-dev         libgdiplus         libicu-dev         libnuma-dev         libssl-dev         libtool         libunwind8         locales         locales-all         python3-dev         python3-pip         sudo         tzdata         unzip     && rm -rf /var/lib/apt/lists/*         && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
 ---> Using cache
 ---> 0e45f8d1a50f
Step 3/7 : ENV LANG en_US.utf8
 ---> Using cache
 ---> dfab0d2e683f
Step 4/7 : RUN ln -sf /usr/bin/python3 /usr/bin/python &&     curl https://bootstrap.pypa.io/get-pip.py -o ./get-pip.py --fail --silent --show-error &&     python ./get-pip.py && rm ./get-pip.py &&     python -m pip install --upgrade pip==20.2 &&     python -m pip install virtualenv==16.6.0 &&     pip download --no-deps helix-scripts --index-url https://dnceng.pkgs.visualstudio.com/public/_packaging/helix-client-prod/pypi/simple &&     pip install ./helix_scripts-*-py3-none-any.whl
 ---> Running in 88eef944eacc
Traceback (most recent call last):
  File "./get-pip.py", line 24226, in <module>
    main()
  File "./get-pip.py", line 199, in main
    bootstrap(tmpdir=tmpdir)
  File "./get-pip.py", line 82, in bootstrap
    from pip._internal.cli.main import main as pip_entry_point
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1147, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1123, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1104, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 541, in spec_from_file_location
  File "/tmp/tmp9_2d_czj/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
```

**Comment by MichaelSimons** [comment]
@MattGal, Can you help get this Dockerfile building again?  Thanks

**Comment by MattGal** [comment]
@MichaelSimons sure, probably will have some cycles tomorrow

**Comment by MattGal** [comment]
It's this issue:  https://github.com/pypa/get-pip/issues/83 . I am dinking around with workarounds now.

**Comment by MattGal** [comment]
https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/404 .  I actually didn't realize these sorts of "python-version-specific" get-pip urls existed.  Since they do, this is a simple workaround when stuff goes sideways.

**Comment by MattGal** [comment]
resolved via https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/404, which serves as a model for if this happens in the future with other OSes stuck on older Python 3.x

**Comment by MichaelSimons** [comment]
Thanks @MattGal!
